// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBex4PVYs5aDKiiLMwDxbwShGPvJ-YcOOo',
    appId: '1:893499279895:web:01e22365ea1e31eb146a52',
    messagingSenderId: '893499279895',
    projectId: 'news-app-7cb6f',
    authDomain: 'news-app-7cb6f.firebaseapp.com',
    storageBucket: 'news-app-7cb6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuSeL73vSxjQab_7sXwnsrbm24nIxew3o',
    appId: '1:893499279895:android:f6f3e94848ecb999146a52',
    messagingSenderId: '893499279895',
    projectId: 'news-app-7cb6f',
    storageBucket: 'news-app-7cb6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCK5Dkq9XTzXBDhVVnAuEVxKj9idmnJ7Q',
    appId: '1:893499279895:ios:09111e52f91c5f14146a52',
    messagingSenderId: '893499279895',
    projectId: 'news-app-7cb6f',
    storageBucket: 'news-app-7cb6f.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCK5Dkq9XTzXBDhVVnAuEVxKj9idmnJ7Q',
    appId: '1:893499279895:ios:09111e52f91c5f14146a52',
    messagingSenderId: '893499279895',
    projectId: 'news-app-7cb6f',
    storageBucket: 'news-app-7cb6f.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBex4PVYs5aDKiiLMwDxbwShGPvJ-YcOOo',
    appId: '1:893499279895:web:fb60e5e5f2f2c0d4146a52',
    messagingSenderId: '893499279895',
    projectId: 'news-app-7cb6f',
    authDomain: 'news-app-7cb6f.firebaseapp.com',
    storageBucket: 'news-app-7cb6f.appspot.com',
  );
}
